-- 004_seed_data.sql
-- Sample data for development and testing

-- Users
INSERT INTO users (email, name, google_id, plan) VALUES
  ('maria.garcia@gmail.com', 'María García', 'google_maria_001', 'pro'),
  ('john.smith@gmail.com', 'John Smith', 'google_john_002', 'free'),
  ('ana.lopez@gmail.com', 'Ana López', 'google_ana_003', 'basic');

-- Student profiles
INSERT INTO student_profiles (user_id, level, total_sessions, streak_days) VALUES
  (1, 'advanced', 25, 12),
  (2, 'beginner', 3, 1),
  (3, 'intermediate', 14, 5);

-- Sessions
INSERT INTO sessions (user_id, agent_type, started_at, ended_at, summary) VALUES
  (1, 'chat', '2026-03-10 09:00:00+00', '2026-03-10 09:30:00+00', 'Practiced past tenses and conditional structures. Minor error with "used to + infinitive". Overall fluent conversation.'),
  (1, 'chat', '2026-03-15 10:00:00+00', '2026-03-15 10:25:00+00', 'Discussed travel experiences. Good use of present perfect. One error with verb form after "used to".'),
  (1, 'voice', '2026-03-18 14:00:00+00', '2026-03-18 14:20:00+00', 'Fluent voice conversation about work life. Pronunciation clear. Suggested practicing linking sounds.'),
  (2, 'chat', '2026-03-20 16:00:00+00', '2026-03-20 16:15:00+00', 'Introductions and basic greetings. Multiple errors with age expression and agreement verbs. Needs reinforcement.'),
  (3, 'chat', '2026-03-12 11:00:00+00', '2026-03-12 11:30:00+00', 'Practiced present perfect vs simple past. Confusion with irregular verbs and word order.'),
  (3, 'voice', '2026-03-19 15:00:00+00', '2026-03-19 15:25:00+00', 'Talked about daily routines and job responsibilities. Good fluency, some subject-verb agreement errors.');

-- Tasks
INSERT INTO tasks (user_id, title, due_date, completed_at, assigned_by_agent) VALUES
  (1, 'Write a paragraph about your weekend', '2026-03-17', '2026-03-16 20:00:00+00', 'chat'),
  (2, 'Practice greetings with Chat Agent', '2026-03-21', NULL, 'chat'),
  (3, 'Record a 2-min voice about your job', '2026-03-25', NULL, 'voice'),
  (3, 'Complete present perfect exercises', '2026-03-14', '2026-03-13 18:00:00+00', 'chat');

-- Grammar notes
INSERT INTO grammar_notes (session_id, error_type, original_text, correction) VALUES
  (4, 'age_expression', 'I have 25 years', 'I am 25 years old'),
  (4, 'false_friend', 'I am agree with you', 'I agree with you'),
  (5, 'verb_tense', 'I go yesterday to the store', 'I went to the store yesterday'),
  (6, 'subject_verb_agreement', 'She don''t like coffee', 'She doesn''t like coffee'),
  (2, 'infinitive_form', 'I used to lived in Madrid', 'I used to live in Madrid');

-- Payments
INSERT INTO payments (user_id, stripe_subscription_id, status, next_billing_date) VALUES
  (1, 'sub_maria_pro_001', 'active', '2026-04-10'),
  (2, NULL, 'free', NULL),
  (3, 'sub_ana_basic_003', 'active', '2026-03-30');

-- Documents (RAG content — embeddings NULL, to be generated by the ingestion pipeline)
INSERT INTO documents (content, embedding, metadata, source_type) VALUES
  (
    'Greetings and Introductions. Common greetings: Hello, Hi, Hey. Good morning, Good afternoon, Good evening. How are you? How''s it going? Introducing yourself: My name is... / I''m... Nice to meet you. I''m from... Common mistakes: Wrong: "I am agree" → Correct: "I agree". Wrong: "I have 25 years" → Correct: "I am 25 years old".',
    NULL,
    '{"level": "beginner", "topic": "greetings", "subtopic": "introductions"}',
    'course'
  ),
  (
    'Present Perfect. Use the present perfect to talk about experiences, changes, and actions that started in the past and continue to the present. Structure: subject + have/has + past participle. Examples: I have visited London. She has worked here for 5 years. Common mistakes: Wrong: "I have go to Paris" → Correct: "I have gone to Paris". Wrong: "She has went home" → Correct: "She has gone home".',
    NULL,
    '{"level": "intermediate", "topic": "verb_tenses", "subtopic": "present_perfect"}',
    'course'
  ),
  (
    'Pricing and Plans. Free plan: 2 chat sessions per week, no voice sessions. Basic plan ($9.99/month): unlimited chat sessions, 3 voice sessions per week. Pro plan ($19.99/month): unlimited chat and voice sessions, priority support, weekly progress reports via email.',
    NULL,
    '{"type": "pricing"}',
    'policy'
  );
